export const TOP_CARDS = [
    { title: 'Trump won, now what?' },
    { title: '2024 Election Results' },
    { title: 'Mention Markets' },
    { title: 'Start Trading' },
];
export const CARDS = [
    {
        title: 'Can Bitcoin reach $100k?',
        desc: 'As of November 22, 2024, Bitcoin is on the cusp of reaching $100,000. The cryptocurrency has recently hit a new all-time high, surpassing $97,000',
        outcomes: ['Yes', 'No'],
        yes: '60%',
        no: '40%',
        poolSize: '$100k',
    },
    {
        title: 'Fed decision in December?',
        desc: 'As of November 22, 2024, Bitcoin is on the cusp of reaching $100,000. The cryptocurrency has recently hit a new all-time high, surpassing $97,000',
        outcomes: ['Yes', 'No'],
        yes: '60%',
        no: '40%',
        poolSize: '$100k',
    },
    {
        title: 'Fed decision in December?',
        desc: 'As of November 22, 2024, Bitcoin is on the cusp of reaching $100,000. The cryptocurrency has recently hit a new all-time high, surpassing $97,000',
        outcomes: ['Yes', 'No'],
        yes: '60%',
        no: '40%',
        poolSize: '$100k',
    },
    {
        title: 'Fed decision in December?',
        desc: 'As of November 22, 2024, Bitcoin is on the cusp of reaching $100,000. The cryptocurrency has recently hit a new all-time high, surpassing $97,000',
        outcomes: ['Yes', 'No'],
        yes: '60%',
        no: '40%',
        poolSize: '$100k',
    },
    {
        title: 'Fed decision in December?',
        desc: 'As of November 22, 2024, Bitcoin is on the cusp of reaching $100,000. The cryptocurrency has recently hit a new all-time high, surpassing $97,000',
        outcomes: ['Yes', 'No'],
        yes: '20%',
        no: '80%',
        poolSize: '$100k',
    },
    {
        title: 'Fed decision in December?',
        desc: 'As of November 22, 2024, Bitcoin is on the cusp of reaching $100,000. The cryptocurrency has recently hit a new all-time high, surpassing $97,000',
        outcomes: ['Yes', 'No'],
        yes: '60%',
        no: '40%',
        poolSize: '$100k',
    },
    {
        title: 'Fed decision in December?',
        desc: 'As of November 22, 2024, Bitcoin is on the cusp of reaching $100,000. The cryptocurrency has recently hit a new all-time high, surpassing $97,000',
        outcomes: ['Yes', 'No'],
        yes: '60%',
        no: '40%',
        poolSize: '$100k',
    },
    {
        title: 'Fed decision in December?',
        desc: 'As of November 22, 2024, Bitcoin is on the cusp of reaching $100,000. The cryptocurrency has recently hit a new all-time high, surpassing $97,000',
        outcomes: ['Yes', 'No'],
        yes: '60%',
        no: '40%',
        poolSize: '$100k',
    },
];
